# -*- coding: utf-8 -*-
"""Financial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u7PNQFxhk7pJgwYW0jhcJPGgtNZD9CDc
"""

import requests
print(requests.__version__)

!pip install -q sentence-transformers transformers faiss-cpu
from sentence_transformers import SentenceTransformer

documents = [
    "Stock markets are influenced by economic indicators such as inflation, interest rates, and employment data.",
    "Higher interest rates usually reduce stock market growth because borrowing becomes expensive for companies.",
    "Machine learning models are used in finance for forecasting, fraud detection, and risk management."
]

embedder = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")
doc_embeddings = embedder.encode(documents)

import faiss
import numpy as np

dimension = doc_embeddings.shape[1]
index = faiss.IndexFlatL2(dimension)
index.add(np.array(doc_embeddings))

from transformers import pipeline

llm = pipeline(
    "question-answering",
    model="distilbert-base-uncased-distilled-squad"
)

def rag_answer(query, k=2):
    query_embedding = embedder.encode([query])
    distances, indices = index.search(np.array(query_embedding), k)

    context = " ".join([documents[i] for i in indices[0]])

    result = llm(
        question=query,
        context=context
    )
    return result["answer"]

rag_answer("Explain economic indicators with examples")